blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Ask a Question
    url: https://github.com/Emran025/shafeea/discussions/new?category=q-a
    about: Please ask and answer questions here.
  - name: ğŸ’¡ Feature Idea
    url: https://github.com/Emran025/shafeea/discussions/new?category=ideas
    about: Share your ideas for new features.
  - name: ğŸ›¡ï¸ Report a Security Vulnerability
    url: ../../SECURITY.md
    about: Please review our security policy for reporting vulnerabilities.
